CREATE TABLE IF NOT EXISTS user_vehicles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    plate VARCHAR(20) NOT NULL,
    owner VARCHAR(50) NOT NULL,
    got VARCHAR(10) NOT NULL DEFAULT 'true',
    NB INT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
